models/cont.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(80))
    email = db.Column(db.String(80))
    phone = db.Column(db.String(100))
    
    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key= "secret_key"
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:cafe2018@localhost/example_db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from models.cont import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)

@contacts.route("/")
def home():
    contacts = Contact.query.all()
    return render_template("index.html", contacts = contacts)

@contacts.route("/new", methods=['POST'])
def create():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']
    
    new_contact = Contact(fullname, email, phone)
    
    db.session.add(new_contact)
    db.session.commit()
    flash("contacto registrado exitosamente", 'info')
    
    return redirect(url_for('contacts.home'))

@contacts.route("/update/<id>", methods=['POST','GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']
        
        db.session.commit()
        flash("contacto actualizado exitosamente!", 'info')
        return redirect(url_for('contacts.home'))
    else:
        return render_template('create.html', contact=contact)

@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash("contacto eliminado exitosamente", 'info')
    return redirect(url_for('contacts.home'))

templates/create.html
<html>

    <form action="/update/{{contact.id}}" method="POST">

        
        <input type="text" name="fullname" placeholder="write your new fullname" value="{{contact.fullname}}"></input>
        
        <input type="text" name="email" placeholder="write your new email" value="{{contact.email}}"></input>
        
        <input type="text" name="phone" placeholder="write your new phone" value="{{contact.phone}}"></input>

        <button>Update</button>
    
    </form>

</html>

templates/index.html
{% with messages = get_flashed_messages() %}

{% if messages%}
    {%for message in messages%}
        {{message}}
    {%endfor%}
{% endif %}

{%endwith%}
<html>

    <form action="/new" method="POST">

        
        <input type="text" name="fullname" placeholder="write your fullname"></input>
        
        <input type="text" name="email" placeholder="write your email"></input>
        
        <input type="text" name="phone" placeholder="write your phone"></input>

        <button>Save</button>
    
    </form>

    <div>
        {% for contact in contacts %}
        <div>
            <h5>{{contact.fullname}}</h5>
            <div>
                <a href="{{ url_for('contacts.update', id=contact.id)}}">Update</a>
                <a href="{{ url_for('contacts.delete', id=contact.id)}}">Delete</a>
            </div>
            <p>{{contact.email}}</p>
            <p>{{contact.phone}}</p>
        </div>
        {% endfor %}
    </div>

</html>